name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Minikube
        run: |
          minikube start
          minikube kubectl -- apply -f manifest/

      - name: Update Container Version
        run: |
          # Obtener la versión actual desde el archivo de manifiesto
          CURRENT_VERSION=$(grep "image:" manifest/deploy.yaml | awk '{print $NF}')

          # Reemplazar la versión con una nueva
          NEW_VERSION="latest"
          sed -i "s/$CURRENT_VERSION/$NEW_VERSION/g" manifest/deploy.yaml

          # Actualizar el despliegue en el clúster
          kubectl apply -f manifest/
