# name: CI

# on:
#   push:
#     branches:
#       - main

# env:
#   IMAGE_NAME: kantox

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2

#     - name: Login to DockerHub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Build and push
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         push: true
#         tags: ${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

#     - name: Repository Dispatch
#       uses: peter-evans/repository-dispatch@v1
#       with:
#         token: ${{ secrets.PAT }}
#         #repository: ${{ github.actor }}/GitOps-Kantox/Docker
#         repository: JaimeHenaoChallange/GitOps-Kantox
#         event-type: new-image
#         client-payload: '{"image": "${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}"}'

name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: kantox

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Docker  # Adjust the path according to the actual location of the Dockerfile
        push: true
        tags: ${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: JaimeHenaoChallange/GitOps-Kantox
        event-type: new-image
        # Sending the image name to the client so it knows where to find the Dockerfile in the 'Docker' folder
        client-payload: '{"image": "${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}", "dockerfile_path": "Docker/"}'

