# name: Actualizar Imagen de Deployment

# on:
#   workflow_run:
#     workflows: ["CI"]
#     types:
#       - completed

# jobs:
#   update-deployment:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repositorio
#       uses: actions/checkout@v2

#     - name: Mostrar Variables de Entorno
#       run: env

#     - name: Listar Archivos en la Raíz
#       run: ls

#     - name: Mostrar Contenido de deployment.yaml
#       run: cat deployment.yaml

#     - name: Debug Git Status
#       run: |
#         git status
#         git log

#     - name: Configurar Identidad de Usuario Git
#       run: |
#         git config user.name "GitHub Actions"
#         git config user.email "actions@github.com"

#     - name: Actualizar Imagen en deployment.yaml
#       run: |
#         NEW_TAG=${{ github.run_number }}
#         sed -i "s|image: jaimehenao8126/kantox-dev:42|image: jaimehenao8126/kantox:${NEW_TAG}|g" deployment.yaml
#         git diff --exit-code deployment.yaml || (git add deployment.yaml && git commit -m "Actualizar imagen en deployment.yaml" && git push)
    
#     - name: Debug Git Diff
#       run: git diff deployment.yaml

name: Actualizar Imagen de Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Actualizar Repositorio Local
      run: git pull origin main

    - name: Checkout Repositorio
      uses: actions/checkout@v2

    - name: Mostrar Variables de Entorno
      run: env

    - name: Listar Archivos en la Raíz
      run: ls

    - name: Mostrar Contenido de deployment.yaml
      run: cat deployment.yaml

    - name: Debug Git Status
      run: |
        git status
        git log

    - name: Configurar Identidad de Usuario Git
      run: |
        git config user.name "Jaime Henao"
        git config user.email "jaimehenao8126@outlook.com"

    - name: Actualizar Imagen en deployment.yaml
      run: |
        NEW_TAG=${{ github.run_number }}
        sed -i "s|image: jaimehenao8126/kantox-dev:42|image: jaimehenao8126/kantox:${NEW_TAG}|g" deployment.yaml
        git diff --exit-code deployment.yaml || (git add deployment.yaml && git commit -m "Actualizar imagen en deployment.yaml" && git push)
    
    - name: Debug Git Diff
      run: git diff deployment.yaml


