name: Update Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: JaimeHenaoChallange/GitOps-Kantox
          ref: main

      - name: Update Deployment
        run: |
          # Obtener la etiqueta de imagen de la salida del trabajo CI
          IMAGE_TAG=$(curl -s "${{ github.event.repository.url }}/actions/runs/${{ github.event.workflow_run.id }}/jobs/build" | jq -r '.steps[] | select(.name == "Build and push") | .outputs.image_tag')
          
          # Actualizar deployment.yaml con la nueva etiqueta de imagen
          sed -i "s|image: .*|image: ${GITHUB_ACTOR}/kantox-dev:${IMAGE_TAG}|" deployment.yaml

          # Hacer commit y push de los cambios
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add deployment.yaml
          git commit -m "Actualizar etiqueta de imagen en deployment.yaml"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.PAT1 }}
