# name: Repository Dispatch

# on:
#   repository_dispatch:
#     types: [new-image]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Update Image Version
#       id: imgupd
#       uses: mikefarah/yq@master
#       with:
#         cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i ./deployment.yaml

#     - uses: stefanzweifel/git-auto-commit-action@v4
#       with:
#         commit_message: Apply image name changes

name: Repository Dispatch

on:
  repository_dispatch:
    types: [new-image]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Image Version
      id: imgupd
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i ./deployment.yaml

    - name: Confirmar Configuración Global de Git
      run: |
        git config --global user.name
        git config --global user.email
        git config --list

    - name: Configurar Usuario de Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit y Push con HTTPS
      run: |
        git add .
        git commit -m "Apply image name changes"
        git remote set-url origin https://${{ secrets.PAT }}@github.com/JaimeHenaoChallange/GitOps-Kantox.git
        git push origin HEAD:${{ github.ref }}
      env:
        YOUR_GITHUB_TOKEN: ${{ secrets.PAT }}


