name: Update Deployment Image

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Display Environment Variables
      run: env

    - name: List Files in Root
      run: ls

    - name: Display Contents of deployment.yaml
      run: cat deployment.yaml

    - name: Configure Git User
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Debug Git Status
      run: |
        git status
        git log

    - name: Get the latest image version
      id: get_latest_image
      run: echo "::set-output name=latest_image::$(grep -E '^ *image:' deployment.yaml | awk '{print $2}' | sort -V | tail -n 1)"

    - name: Update Image in deployment.yaml
      run: |
        NEW_TAG=${{ github.run_number }}
        sed -i "s|image: ${{ steps.get_latest_image.outputs.latest_image }}|image: jaimehenao8126/kantox:${NEW_TAG}|g" deployment.yaml
        # Check if there are changes to commit
        git diff --exit-code deployment.yaml || (git add deployment.yaml && git commit -m "Update image in deployment.yaml" && git push)

    - name: Debug Git Diff
      run: git diff deployment.yaml

# Add error handling and conditions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
