name: Update Image in Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure Git User
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Get Latest Image Version
      id: get_latest_image
      run: echo "::set-output name=latest_image::$(grep -E '^ *image:' deployment.yaml | awk '{print $2}' | sort -V | tail -n 1 | cut -d ':' -f 2 | cut -d 'v' -f 2)"

    - name: Update Image in deployment.yaml
      run: |
        NEW_TAG=$((NEW_TAG + 1))
        sed -i "s|image: ${{ steps.get_latest_image.outputs.latest_image }}|image: jaimehenao8126/kantox:v${NEW_TAG}|g" deployment.yaml
        git diff --exit-code deployment.yaml || (git add deployment.yaml && git commit -m "Update image in deployment.yaml" && git push)
