name: Actualizar Imagen de Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositorio
      uses: actions/checkout@v2

    - name: Listar Archivos en la Raíz
      run: ls

    - name: Actualizar Imagen en deployment.yaml
      run: |
        sed -i 's|image: jaimehenao8126/kantox-dev:26|image: jaimehenao8126/kantox-dev:${{ github.run_number }}|g' deployment.yaml
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@example.com"
        git diff --exit-code deployment.yaml || (git add deployment.yaml && git commit -m "Actualizar imagen en deployment.yaml" && git push https://github.com/${{ github.repository }}.git)
      env:
        GH_TOKEN: ${{ secrets.KUBE }}






